"""initial

Revision ID: d33aba82a0e8
Revises: 
Create Date: 2026-07-17 12:51:59.029232
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

revision: str = 'd33aba82a0e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hs_codes',
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('chapter', sa.String(length=2), nullable=True),
    sa.Column('heading', sa.String(length=4), nullable=True),
    sa.Column('subheading', sa.String(length=6), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('br_number', sa.String(length=50), nullable=True),
    sa.Column('subscription_tier', sa.String(length=20), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('usage_current', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('br_number')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('api_key', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_org_id'), 'audit_logs', ['org_id'], unique=False)
    op.create_table('declarations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=True),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('confidence_avg', sa.Float(), nullable=True),
    sa.Column('decl_number', sa.String(length=50), nullable=True),
    sa.Column('consignor_name', sa.String(length=255), nullable=True),
    sa.Column('consignor_address', sa.Text(), nullable=True),
    sa.Column('consignee_name', sa.String(length=255), nullable=True),
    sa.Column('consignee_address', sa.Text(), nullable=True),
    sa.Column('port_of_loading', sa.String(length=100), nullable=True),
    sa.Column('port_of_discharge', sa.String(length=100), nullable=True),
    sa.Column('incoterms', sa.String(length=10), nullable=True),
    sa.Column('declared_currency', sa.String(length=3), nullable=True),
    sa.Column('total_declared_value', sa.Float(), nullable=True),
    sa.Column('gross_weight', sa.Float(), nullable=True),
    sa.Column('net_weight', sa.Float(), nullable=True),
    sa.Column('number_of_packages', sa.Integer(), nullable=True),
    sa.Column('container_number', sa.String(length=50), nullable=True),
    sa.Column('country_of_origin', sa.String(length=100), nullable=True),
    sa.Column('country_of_destination', sa.String(length=100), nullable=True),
    sa.Column('transport_mode', sa.String(length=50), nullable=True),
    sa.Column('commercial_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_declarations_org_id'), 'declarations', ['org_id'], unique=False)
    op.create_table('commodities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('declaration_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hs_code', sa.String(length=20), nullable=True),
    sa.Column('hs_code_confidence', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('declared_value', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('country_of_origin', sa.String(length=2), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.ForeignKeyConstraint(['declaration_id'], ['declarations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commodities_declaration_id'), 'commodities', ['declaration_id'], unique=False)
    op.create_table('wco_declarations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('declaration_id', sa.UUID(), nullable=False),
    sa.Column('wco_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('wco_xml', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.String(length=20), nullable=True),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tsw_reference', sa.String(length=50), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['declaration_id'], ['declarations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wco_declarations_declaration_id'), 'wco_declarations', ['declaration_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wco_declarations_declaration_id'), table_name='wco_declarations')
    op.drop_table('wco_declarations')
    op.drop_index(op.f('ix_commodities_declaration_id'), table_name='commodities')
    op.drop_table('commodities')
    op.drop_index(op.f('ix_declarations_org_id'), table_name='declarations')
    op.drop_table('declarations')
    op.drop_index(op.f('ix_audit_logs_org_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('organizations')
    op.drop_table('hs_codes')
    # ### end Alembic commands ###
